# Global LLM configuration
[llm]
model = "deepseek-r1-250120"
#model = "deepseek-v3-250324"
#model = "deepseek-v3-241226"
base_url = "https://ark.cn-beijing.volces.com/api/v3"
api_key = "d5d9437dd7-87effe-4816-9ed9-273e447ec84e"
max_tokens = 8192
temperature = 0.4

# Optional configuration for specific LLM models
[llm.vision]
model = "deepseek-r1-250120"
#model = "deepseek-v3-250324"
#model = "deepseek-v3-241226"
base_url = "https://ark.cn-beijing.volces.com/api/v3"
api_key = "d5d9437dd7-87effe-4816-9ed9-273e447ec84e"

# Server configuration
[server]
host = "0.0.0.0"
port = 5172
